### PR TITLE
Update runtime.md

### PR DESCRIPTION
**Pull request by hannibalhuang**
Add a section on Modification

### CODE REVIEW

**Comment by philips** [comment]
@hannibalhuang Was this an accidental PR? What are you trying to express with modify?

**Comment by hannibalhuang** [comment]
@philips For life cycle management usually we got create,modify and terminate, my thinking was simply adding a modification section currently is missing. But if there is more to come then I'm willing to close it :)

**Comment by philips** [comment]
@hannibalhuang what sorts of things do you want to modify? In the create side it is mostly setting up namespace before exec'ing the target app. On the terminate side it is cleaning up said namespaces.

**Comment by hannibalhuang** [comment]
@philips so what I have in mind are stuff like change container size due to Mesos policy, storage back-end change, network port change and so forth.

**Comment by philips** [comment]
@hannibalhuang I think it is a bit early for any of these concepts. At some point we might turn the discussion towards things like updating cgroups isolation, etc.

**Comment by hannibalhuang** [comment]
@philips sounds reasonable to me :) BTW updating isolation is still one kind of modification operation right?

**Comment by jonboulle** [comment]
@hannibalhuang see #17

**Comment by philips** [comment]
I am going to close this in favor of #17.

**Pull request closed without merging**
