### PR TITLE
Fix LinuxRuntime field

### PR DESCRIPTION
**Pull request by LK4D4**
ping @mrunalp @crosbymichael

### CODE REVIEW

**Comment by jonboulle** [comment]
more context? this is essentially breaking with the [config.json convention for platform-specific configuration](https://github.com/opencontainers/specs/blame/e9cb5644fa03cc66f46657266b724f74ee86b04e/config.md#L95) - so at a minimum, should have an equivalent stipulation (e.g. in the currently-underspecified runtime.md) - but I'm not clear from this PR why this change is necessary

**Comment by LK4D4** [comment]
@jonboulle First it isn't working at all. Second it's runtime config and not runtime. I choose name for consistency because actually type name is `RuntimeLinux`. I don't care to name it `Linux`, but because other field named `RuntimeSpec` and not `Spec`, maybe it makes sense as it is.

**Comment by LK4D4** [comment]
Actually I'm sorta lost about naming :) Any ideas are welcome

**Comment by crosbymichael** [comment]
i like just `"linux"`

**Comment by jonboulle** [comment]
I understand that runtime is distinct from config; I was highlighting that a) this introduces an inconsistency between the two for platform-specific configuration, and b) that the runtime configuration is not well specified outside the go implementation here. As for "it isn't working at all", it's still impossible to tell what this means without context...

**Comment by LK4D4** [comment]
@jonboulle It's another golang type, not what was expected.

**Comment by LK4D4** [comment]
@jonboulle @crosbymichael PTAL

**Comment by mrunalp** [comment]
LGTM

**Comment by jonboulle** [comment]
lgtm!

**Comment by dqminh** [comment]
LGTM

**Comment by LK4D4** [comment]
I'm merging then.

**Pull request merged**
