### PR TITLE
use the lifecycle states to define the hooks

### PR DESCRIPTION
**Pull request by laijs**

### CODE REVIEW

**Comment by hqhq** [comment]
Lifecycle modification is on going in #231 , this PR needs to be hold on.

**Comment by laijs** [comment]
The intention of this pr is, as its title said, using the lifecycle states to define the hooks.
it has something(changing to the lifecycle) conflicting with #231, but this part is unimportant.
I will remove this part ("remove `(process)` from lifecycle states" and cross reference), and re-summit the pr. thx.

**Comment by vbatts** [comment]
This looks fine for the most part. The switch from "exits" -> "stopped" seems to imply the hooks may get triggered before the container has fully ended. Like if the pid(s) are sent signals to terminate, but they hang in a Wait state, would the hooks still get called?

**Comment by philips** [comment]
This PR is too confusing. "container is started" is confusing: the only way it has meaning is if we agree on a term that isn't "container" for the application process.

**Comment by vbatts** [comment]
#231 is merged. Please update.

**Pull request closed without merging**
