### PR TITLE
ReadMe: Update content to match print order

### PR DESCRIPTION
**Pull request by RobDolinMS**
Update the Table of Contents section of the ReadMe.md to match the order of the merged MarkDown files in the printable HTML and PDF outputs

Signed-off by Rob Dolin <RobDolin@microsoft.com>

### CODE REVIEW

**Comment by RobDolinMS** [comment]
Tagging @vbatts so he sees this before generating the v0.4 merged printable files.

**Comment by wking** [comment]
It looks like 7d55248cc is missing a Signed-off-by [1], and the README
self-reference is a bit odd, but other than that, this looks good to
me.

[1]: https://travis-ci.org/opencontainers/specs/jobs/114658568

**Comment by RobDolinMS** [comment]
Thanks @wking and @vbatts.  I made the edit via GitHub on the web so signed-off by is in my commit notes which show as the first comment on this thread.  Self-reference to the ReadMe is intentional as this also doubles as the Table of Contents for the merged HTML and PDF docs when we cut a version.

**Comment by mrunalp** [comment]
@RobDolinMS Could you ammend the commit and repush?
```
git commit --amend --signoff
```

**Comment by vbatts** [comment]
carried this PR to https://github.com/opencontainers/specs/pull/337 and fixed the cap-sensitive file names too.

**Pull request closed without merging**
