### PR TITLE
Fix Windows path escaping in example mount JSON

### PR DESCRIPTION
**Pull request by titanous**

### CODE REVIEW

**Comment by philips** [comment]
@titanous ha, what a mess of escaping. Thank you!

**Comment by philips** [comment]
@titanous actually, since this is in a code-block shouldn't all of the escaping be removed?

**Comment by titanous** [comment]
@philips This is JSON escaping, not markdown escaping.

**Comment by philips** [comment]
@titanous gah, you are right! Thanks!

**Pull request merged**
