### PR TITLE
README: Document pre-meeting agenda alteration

### PR DESCRIPTION
**Pull request by wking**
On Sat, Aug 08, 2015 at 08:23:21AM -0400, Vincent Batts [wrote][1]:
> We said the topics would be proposed on this list. Discussion notes have
> been shared as a Google doc so far. I'm not opposed to markdown notes, but
> initially that just seems like an repo to me.

While touching this paragraph, I also re-wrapped it to match
README.md#markdown-style.

[1]: https://groups.google.com/a/opencontainers.org/d/msg/dev/41jZ9Qe7R5c/ZInajC_0DgAJ

### CODE REVIEW

**Comment by wking** [comment]
And the earlier discussion @vbatts is referencing is probably:

On Wed, Aug 05, 2015 at 11:57:59AM -0700, Mrunal Patel [wrote][1]:
> We could also have guests on the hangout if they have some important
> topic to present. We can decide that on the topics being discussed
> in the mailing list.

[1]: https://groups.google.com/a/opencontainers.org/d/msg/dev/JsXgi4kxkBg/Gw7GvPodDgAJ

**Comment by vbatts** [comment]
Also on the last discussion call as well.

**Comment by wking** [comment]
On Sat, Aug 08, 2015 at 02:44:08PM -0700, Vincent Batts wrote:
> Also on the last discussion call as well.

Ah, thanks.  I've added references to [1,2] to my commit message.

[1]: https://docs.google.com/document/d/1a5UW7MRLVaUDEjuQmRudYMZcPV0bBtPD2QEOLT_3zi0/edit?usp=sharing
[2]: https://plus.google.com/events/cqfpicicbnra9mv6kvpj0mb24u4

**Comment by vbatts** [comment]
LGTM

**Comment by wking** [comment]
On Mon, Aug 10, 2015 at 12:45:22PM -0700, Vincent Batts wrote:
> Merged #102.

While I (obviously ;) think this was good to land, I'm not sure if it
should have waited for a second maintainer LGTM or not.  The runC
maintainer guide currently requires two maintainer LGTMs [1], and as
far as I can tell that document currently applies to all OCI projects
(see opencontainers/web#5 and [2]).  In fact, I'm not even clear on
whether or not you're officially a maintainer (opencontainers/web#5
;).

[1]: https://github.com/opencontainers/runc/blob/9be9157fc5cd9cf59c155fe194a0acc5f1e6f926/MAINTAINERS_GUIDE.md#who-decides-what
[2]: https://github.com/opencontainers/web/pull/4#issuecomment-129032943

**Comment by vbatts** [comment]
I agree a lot of this could be more clear. And as runc is a carried over project, there is likely updates and clarification needed to it around this topic as well.

**Pull request merged**
