### PR TITLE
Bump v0.4.0

### PR DESCRIPTION
**Pull request by vbatts**

### CODE REVIEW

**Comment by vishh** [comment]
LGTM

**Comment by wking** [comment]
On Wed, Mar 09, 2016 at 11:09:15AM -0800, Vincent Batts wrote:
>   * version: v0.4.0
>   * version: bump v0.5.0-dev

Changelog?  Should I work one up and post a Gist like I did for
v0.3.0?

**Comment by vbatts** [comment]
@wking yes please!

**Comment by wking** [comment]
Did you want to rebase around #331 (landed in master since this branch
broke away)?  Are we freezing master until this lands?

**Comment by vbatts** [comment]
i'll rebase once the milestone is clear.

**Comment by vbatts** [comment]
rebased with @wking changelog

**Comment by crosbymichael** [comment]
last commit lacks DCO

**Comment by wking** [comment]
On Wed, Mar 09, 2016 at 04:51:30PM -0800, Michael Crosby wrote:
> last commit lacks DCO

Oops.  I just pushed 8901446 to [1], along with ChangeLog updates
covering changes after 3b7c15d (@vbatt's initial branching-off point)
through eea2a6c (his current branching-off point).

[1]: https://github.com/wking/opencontainer-specs/tree/v0.4.0-changelog

**Comment by vbatts** [comment]
just rebased again, and added a couple more items

**Comment by wking** [comment]
On Thu, Mar 10, 2016 at 10:56:03AM -0800, Vincent Batts wrote:
> just rebased again, and added a couple more items

I'd mention #335 and #337 as well, but ab44e37 looks fine to me.

**Comment by vbatts** [comment]
Those seem minor enough.

PTAL

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
