### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RobDolinMS**
Minutes posted to mailing list --> Minutes posted to wiki; Clarified that this includes all past calls.

### CODE REVIEW

**Comment by philips** [comment]
Can we post to both the mailing list and wiki?

**Comment by wking** [comment]
On Sun, Aug 30, 2015 at 03:28:27PM -0700, Rob Dolin wrote:
> Minutes posted to mailing list --> Minutes posted to wiki;

I floated something like this in my initial version of #116
(61930a2a), but @vbatts suggested we hold off until we've been posting
to the wiki for longer [1].

[1]: https://github.com/opencontainers/specs/pull/116#issuecomment-135187599

**Comment by RobDolinMS** [comment]
I agree with @philips that we should BOTH post to mailing list and wiki.  PR updated.

**Comment by dqminh** [comment]
LGTM

**Comment by vbatts** [comment]
I really want to like the wiki. and it is more discoverable than the google docs folder. but the wiki syntax is awful. Markdown is fine. But, for instance, most wiki's have nested pages, like `meeting-notes/2015-07-22` and when you go to the page `meeting-notes` you can see its children, but github wiki is a flat structure (no directories). And there is no "automatic lists of pages", so as the number of pages increases, then to keep track of them, there would have to be a separately edited page linking to each new page.

**Comment by wking** [comment]
On Thu, Sep 03, 2015 at 12:18:29PM -0700, Vincent Batts wrote:
> But, for instance, most wiki's have nested pages, like
> `meeting-notes/2015-07-22` and when you go to the page
> `meeting-notes` you can see its children, but github wiki is a flat
> structure (no directories).

I haven't used GitHub's wiki engine enough to know how this gets done
(maybe it's coded by hand) but the docs show a nested TOC [1].

[1]: https://help.github.com/articles/about-github-wikis/

**Comment by vbatts** [comment]
TOC is different. It points to anchors on a same page, not nested pages...

**Comment by wking** [comment]
On Thu, Sep 03, 2015 at 12:40:10PM -0700, Vincent Batts wrote:
> TOC is different. It points to anchors on a same page, not nested
> pages...

Ah, bummer.

**Comment by philips** [comment]
@vbatts maybe we can just agree on some naming standard for posting to the mailing list and then just have a search URL here for people to hunt them down like: https://groups.google.com/a/opencontainers.org/forum/#!searchin/dev/minutes

**Comment by vbatts** [comment]
fair. I mean, the google docs folder is viewable to the world and can have
comments. I'm down for whatever, really. Convenience is nice. :-)

**Comment by vbatts** [comment]
Just did a bit of cleanup and layout. No magic. This is tedious. 
https://github.com/opencontainers/specs/wiki

Thoughts?

**Comment by philips** [comment]
@vbatts I mean honestly I would just say "search the mailing list" and leave it at that until someone complains. Seems like a lot of work for not much gain.

**Comment by vbatts** [comment]
LGTM for now. Though the wiki ... meh.

**Comment by laijs** [comment]
The update doesn't contain 3 different update intentions, using 3 commit for it is bad.
The pr should be squashed into one commit.

**Comment by vbatts** [comment]
@RobDolinMS squash your commits for merge

**Comment by mrunalp** [comment]
LGTM

**Pull request closed without merging**
