### PR TITLE
Remove the state directory as we now have a state operation instead

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by vbatts** [comment]
Oh good. I thought we had already done this!
LGTM

**Comment by wking** [comment]
We probably also want to remove [1] (found by grepping for /run).

[1]: https://github.com/opencontainers/specs/blob/5a606f46042e026fef5f6029511f68cbf55d251e/state.go#L6

**Comment by mrunalp** [comment]
@wking Updated.

**Comment by crosbymichael** [comment]
LGTM

**Comment by wking** [comment]
On Tue, Mar 08, 2016 at 10:36:40AM -0800, Mrunal Patel wrote:
> @wking Updated.

Thanks :).  16c09954 looks good to me.

**Pull request merged**
