### PR TITLE
v0.3.0

### PR DESCRIPTION
**Pull request by vbatts**
where 25cbfc4 is the tagged v0.3.0 release and changelog from https://gist.github.com/wking/4ee11057828d82a6e3d2

### CODE REVIEW

**Comment by wking** [comment]
c450676625 looks good to me.

**Comment by crosbymichael** [comment]
LGTM

**Comment by vishh** [comment]
LGTM

**Comment by wking** [comment]
On Thu, Feb 04, 2016 at 05:28:35PM -0800, Vish Kannan wrote:
> Merged #321.

I guess @vbatts will drop a tag on 25cbfc4 when he gets up in the
morning ;).

**Comment by mrunalp** [comment]
Nice :+1:

**Pull request merged**
