### PR TITLE
implementations: Add links to kunalkushwaha/octool and mrunalp/ocitools

### PR DESCRIPTION
**Pull request by wking**
Details in the commit messages, but basically, if we've heard of an
OCI-related tool, I think we should be linking it from here ;).

@kunalkushwaha and @mrunalp, I've done my best at one-line summaries
based on your READMEs, but I'm happy to reroll these commits if you
prefer different phrasing (just tell me what to put in ;).

### CODE REVIEW

**Comment by kunalkushwaha** [comment]
@wking Thanks for adding the link. Description looks good :)

**Comment by mrunalp** [comment]
LGTM

**Comment by mrunalp** [comment]
Maybe squash the commits?

**Comment by wking** [comment]
On Wed, Oct 07, 2015 at 11:12:57AM -0700, Mrunal Patel wrote:
> Maybe squash the commits?

The two link additions in #195 seem orthogonal (e.g. I could see
someone pushing back on one link and not the other).  Would you still
like them squashed into one commit?

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
