### PR TITLE
Appropriately mark optional fields as omitempty

### PR DESCRIPTION
**Pull request by jonboulle**
Signed-off-by: Jonathan Boulle <jonathanboulle@gmail.com>

per https://github.com/opencontainers/specs/pull/282#issuecomment-167134101

### CODE REVIEW

**Comment by hqhq** [comment]
LGTM

**Comment by arcnmx** [comment]
Oh, one other item I forgot about that should be `omitempty` is runtime/linux's `rootfsPropagation`.

**Comment by hqhq** [comment]
@arcnmx Thanks, @jonboulle Can you update for that? Thanks.

**Comment by jonboulle** [comment]
done

**Comment by hqhq** [comment]
@jonboulle You need to sign your commit.

**Comment by jonboulle** [comment]
Sigh. Done.

**Comment by hqhq** [comment]
Thanks, still LGTM.

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
