### PR TITLE
Add license and DCO information for contributions

### PR DESCRIPTION
**Pull request by crosbymichael**
This adds the apache 2 license and DCO information for contributions to this repository. 

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by philips** [comment]
The Signed-off-by process is sort of annoying and arguably unnecessary when we have identities like Github profiles. I am OK doing it if everyone feels more comfortable with it.

**Comment by crosbymichael** [comment]
@philips it's not that annoying, it's only an extra `-s` when you commit in git.

Do you disagree with the DCO in general or just the signed off part?

**Comment by philips** [comment]
@crosbymichael just the signed off part, the DCO is fine.

**Comment by crosbymichael** [comment]
@philips ok, thanks.  Let me see if I can talk to anyone at the linux foundation to see if its ok for us to remove the signoff part as all the pull requests will come from github.

**Comment by crosbymichael** [comment]
I asked and for now we should keep the signoff until we look into this more on the foundation side.  They said we will need to get all the parties to agree and make sure that this is ok with them because even though we can use github profiles for identify the signoff is an acknowledgement of the DCO with the submission.  

So lets keep this for now and look into it more on the legal side.

**Comment by mrunalp** [comment]
LGTM

**Comment by philips** [comment]
lgtm

**Pull request merged**
