### PR TITLE
Correct version from 0.1.0 to 0.1.1

### PR DESCRIPTION
**Pull request by zenlinTechnofreak**
Correct version from 0.1.0 to 0.1.1
Signed-off-by: LinZhinan(Zen Lin) <linzhinan@huawei.com>

### CODE REVIEW

**Comment by wking** [comment]
On Wed, Sep 16, 2015 at 06:55:03PM -0700, LinZhinan(Zen Lin) wrote:
> Correct version from 0.1.0 to 0.1.1

Duplicate of #183?  I was suggesting we bump/tag 0.1.2 to avoid
confusion.  What tag would you use after bumping to 0.1.1?

**Comment by zenlinTechnofreak** [comment]
@wking, my suggestion is bumping to 0.1.2, guys maybe would like to consider the version is the same as de before one, anyway, once we have not release tag 0.1.2, the specs version should not be considered as 0.1.2.

Now, we just release the tag v0.1.1, so we are better to keep consist with it.
what about other considring?

**Comment by laijs** [comment]
The tag object should reference to the commit which changed the version number.
It is too late to change the version to 0.1.1. (we already have the tag).

**Comment by crosbymichael** [comment]
ping @vbatts

**Comment by vbatts** [comment]
lol. Cold medicine is crazy stuff, y'all.

**Comment by vbatts** [comment]
We can not change the tag, and nothing is strictly requiring this parity yet, and i'm not sure that there will be a _need_ for a `v0.1.2` besides squaring up this version.
I am inclined to make it some kind of dev-cycle indicator for `v0.2.0`.

Like
```diff
diff --git a/version.go b/version.go
index 3e722a5..d55f9b5 100644
--- a/version.go
+++ b/version.go
@@ -8,7 +8,7 @@ const (
        // VersionMinor is for functionality in a backwards-compatible manner
        VersionMinor = 1
        // VersionPatch is for backwards-compatible bug fixes
-       VersionPatch = 0
+       VersionPatch = 99
 )
 
 // Version is the specification version that the package types support.
```

or 
```diff
diff --git a/version.go b/version.go
index 3e722a5..d984121 100644
--- a/version.go
+++ b/version.go
@@ -12,4 +12,4 @@ const (
 )
 
 // Version is the specification version that the package types support.
-var Version = fmt.Sprintf("%d.%d.%d", VersionMajor, VersionMinor, VersionPatch)
+var Version = fmt.Sprintf("%d.%d.%d-dev", VersionMajor, VersionMinor, VersionPatch)
```


Personally, I prefer the former as it is strictly comparable and indicative of prerelease.

**Comment by wking** [comment]
On Mon, Sep 21, 2015 at 08:39:16AM -0700, Vincent Batts wrote:
> I am inclined to make it some kind of dev-cycle indicator for `v0.2.0`.

I think the semver-2.0 phrasing for that would be 0.2.0-rc.1 or
similiar (see §9 and 11 [1]).  If 0.2.0 is just around the corner, I'm
fine just waiting for it (no bump at all).  But unless we're
interested in doing a pre-2.0 feature freeze while we get review on
the release-candidate, I'd rather avoid pre-release versions.

Hopefully our version cadence is fast enough that folks aren't tempted
to build off an unreleased version of the spec.

[1]: http://semver.org/

**Comment by vbatts** [comment]
@zenlinTechnofreak lets just change the minor to `2` for now, and leave the patch as `0`. Then the tree will be ready for the next tagging (whenever that is).

**Comment by zenlinTechnofreak** [comment]
I have made a err operations on closing this PR,  but have created a new one for it,
Change version from 0.1.0 to 0.2.0 #203.

Thanks.

**Pull request closed without merging**
