### PR TITLE
*: remove superfluous comma in code-of-conduct

### PR DESCRIPTION
**Pull request by jonboulle**
Signed-off-by: Jonathan Boulle <jonathanboulle@gmail.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
LGTM

**Comment by vbatts** [comment]
oh, I thought it was reflecting the possession? How do I english?

**Comment by vbatts** [comment]
LGTM

**Comment by jonboulle** [comment]
Possession of the singular "OpenContainer" makes no sense if everywhere else you're referring to the (community?) in the plural. You could go with the somewhat awkward "OpenContainers'" or even more awkward "OpenContainers's" but there's really no need for the possessive in this context.

**Comment by vbatts** [comment]
ah, then it would be OpenContainers'

**Comment by jonboulle** [comment]
did you even read my second sentence? :P

**Comment by wking** [comment]
Or we could just go with “Code of Conduct” ;).  Whose code should be
clear from the context (e.g. the URL starts with
https://github.com/opencontainers/specs/…).

**Comment by vbatts** [comment]
@jonboulle because

**Pull request merged**
