### PR TITLE
Makefile: add a target to run tests

### PR DESCRIPTION
**Pull request by vbatts**
For now, just vet and lint. But would like to include the commit
validator, once a good range is selectable.

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by wking** [comment]
On Thu, Jan 07, 2016 at 12:33:19PM -0800, Vincent Batts wrote:
> But would like to include the commit validator, once a good range is
> selectable.

With reliable Git configs, I'd replace ${TRAVIS_COMMIT_RANGE} with:

  @{upstream}..HEAD

although for me, @{upstream} is usually my *downstream* GitHub
repository (because I use ‘hub pull-request’ [1]).  Git lets you
distinguish between push and pull repositories (branch.<name>.remote
and branch.<name>.pushremote), but does not seem to allow that
distinction for branches (as of 2.7.0).

Alternatively, we could assume that all branches are being developed
for opencontainers/specs' master, so:

  REMOTE = $(shell git remote -v | sed -n 's|^\([^[:space:]]*\)[[:space:]].*github.com/opencontainers/specs.*|\1|p' | head -n1)
  …
  .gitvalidation:
      git-validation -run DCO,short-subject -v -range $(REMOTE)/master..HEAD

I'm not sure which is more reliable:

a. @{upstream} actually pointing at the upstream branch, or
b. ‘master’ being the right upstream branch and
   i. branch.<name>.remote actually having the upstream remote name, or
   ii. sed'ing through ‘git remote -v’ to find the right remote name

Alternatively, you could just require folks to set UPSTREAM
explicitly, and guess it's ‘@{upstream}’ or origin/master, or
whatever:

  UPSTREAM = @{upstream}
  …
  .gitvalidation:
      git-validation -run DCO,short-subject -v -range $(UPSTREAM)..HEAD

See #216 for why I prefer two dots to three.

[1]: https://hub.github.com/

**Comment by crosbymichael** [comment]
LGTM

**Comment by vishh** [comment]
LGTM

**Comment by philips** [comment]
LGTM

**Pull request merged**
