### PR TITLE
Update Typo in ROADMAP.md

### PR DESCRIPTION
**Pull request by coolsvap**

### CODE REVIEW

**Comment by vbatts** [comment]
looks good, but the commit needs to be signed (DCO)

**Comment by hqhq** [comment]
@coolsvap https://github.com/opencontainers/specs/blob/master/README.md#sign-your-work

**Comment by coolsvap** [comment]
@vbatts signed!

**Comment by hqhq** [comment]
@coolsvap Sorry your SOB is still not valid, you need to add angle brackets for your email, something like: `Signed-off-by: Swapnil Kulkarni <me@coolsvap.net>`.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
