### PR TITLE
Example lists "root' but text mentions "bundlePath"

### PR DESCRIPTION
**Pull request by nponeccop**

### CODE REVIEW

**Comment by hqhq** [comment]
@nponeccop Can you sign your commit? Thanks.

**Comment by nponeccop** [comment]
I remember doing that in the past but now somehow cannot google how to sign-off my existing commit. Can you help or find a reference?

**Comment by vbatts** [comment]
@nponeccop `git commit --amend --signoff`

**Comment by hqhq** [comment]
@nponeccop There is instruction in [README.md](https://github.com/opencontainers/specs/blob/master/README.md#sign-your-work)

**Comment by wking** [comment]
On Sun, Nov 29, 2015 at 03:00:09AM -0800, nponeccop wrote:
>   * Example lists "root' but text mentions "bundlePath"

Cross-linking #206, so folks reading either PR can find the related
change.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
