### PR TITLE
MAINTAINERS: add tianon per the charter

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by vbatts** [comment]
https://www.opencontainers.org/charter/

ping @crosbymichael @mrunalp @LK4D4 @philips

**Comment by crosbymichael** [comment]
LGTM

**Comment by tianon** [comment]
:innocent:

**Comment by tianon** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
