### PR TITLE
runtime: config: linux: Remove trailing comma in namespaces json example

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by dqminh** [comment]
LGTM

**Comment by laijs** [comment]
I hope the trailing comma is kept.

**Comment by runcom** [comment]
Why? Isn't it invalid json that way?

**Comment by laijs** [comment]
Yes, it is invalid with trailing comma.
LGTM

**Comment by wking** [comment]
75cb11ce4 looks good to me.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
