### PR TITLE
make rootfs mount propagation mode settable

### PR DESCRIPTION
**Pull request by rootfs**
this is based on discussion on https://github.com/opencontainers/specs/issues/56

@mrunalp @philips

### CODE REVIEW

**Comment by philips** [comment]
cc @crosbymichael

**Comment by mrunalp** [comment]
LGTM

**Comment by lizf-os** [comment]
no updates to config-linux.md?

**Comment by rootfs** [comment]
updated @lizf-os

**Comment by LK4D4** [comment]
Definitely makes sense for linux
LGTM

**Pull request merged**
