### PR TITLE
Move User struct to spec.go

### PR DESCRIPTION
**Pull request by gao-feng**
Otherwise User struct will not be found on other platform

Signed-off-by: Gao feng <feng@hyper.sh>

### CODE REVIEW

**Comment by lizf-os** [comment]
Why don't you add spec_xxx.go to support other platforms? I don't think this User struct is applicable for Windows.

**Comment by gao-feng** [comment]
@lizf-os Process in spec.go references to User

**Comment by dqminh** [comment]
I think it's better to have different user definition for different platforms. I think it's enough to only have `user_unix` and `user_windows`, but conflating the unix default to spec.go is not a good idea

**Comment by mrunalp** [comment]
@gao-feng Thanks for your PR. However, this was discussed earlier and it made sense to have a separate per platform User struct as it doesn't seem very portable right now. When we have more implementations, we will consider abstracting it and moving it into platform independent section if it makes more sense.

**Comment by mrunalp** [comment]
Closing this for now. We will reopen it in the future. Thanks!

**Pull request closed without merging**
