### PR TITLE
Add oom_score_adj to the runtime Spec.

### LINKED ISSUE #114: Support for Quality of Service
The API has to let users express the notion of priority among containers. Consider the case when a web server is run alongside a logging container. The web-server is more important than the logging side-car container. When there is a resource crunch, the user doesn't mind killing one of the lower priority containers, which is logging in this case. Ideally, if all containers were to be run with limits, this might not be necessary. In reality though, setting limits is hard and users tend to over provision resources and that leads to poor resource utilization.

Since this notion of priority can be expressed in different ways, I propose letting users handle cgroup management and only expose the following knobs:

1. **CgroupsPath** - This lets users manage cgroup hierarchies. 

2. **OomScoreAdj** - Apply a custom 'oom_score_adj' to the init process of the container.

### PR DESCRIPTION
**Pull request by vishh**
Fixes #114

### CODE REVIEW

**Comment by vishh** [comment]
cc @mrunalp

**Comment by wking** [comment]
Are we not happy with the pre-start hook approach to this?  See #115
and [1].  If not, can someone give more details about where my #115
decision tree breaks down?  Is the explicit field approach somehow
easier to use than a pre-start hook?  If so, how?

[1]: https://github.com/opencontainers/specs/issues/114#issuecomment-137170642

**Comment by mrunalp** [comment]
@vishh Missing Signed-off-by (causing the build to fail).

**Comment by vishh** [comment]
@wking: https://github.com/opencontainers/specs/issues/114#issuecomment-147500395

**Comment by mrunalp** [comment]
LGTM @LK4D4 @crosbymichael ping

**Comment by vbatts** [comment]
LGTM for now. (the cgroups structures had a good deal of discussion)

**Pull request merged**
