### PR TITLE
Seccomp should be optional

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
Should this also be a pointer?

**Comment by mrunalp** [comment]
@crosbymichael Yes, updated.

**Comment by crosbymichael** [comment]
LGTM

**Comment by wking** [comment]
On Mon, Mar 07, 2016 at 04:45:40PM -0800, Mrunal Patel wrote:
>   * Seccomp should be optional

And potentially shifted to the process config [1,2]?

[1]: https://github.com/opencontainers/specs/pull/329/files#r54785746
[2]: https://github.com/opencontainers/specs/pull/325#issuecomment-191471866

**Comment by mrunalp** [comment]
@wking I think that could be discussed separately from this PR.

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
