### PR TITLE
Regenerate ffjson for Timeout field

### PR DESCRIPTION
**Pull request by crosbymichael**
Just from the ordering of the commits this was missed in the PR when it was merged.  

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
Why travis so mad?

**Comment by wking** [comment]
On Fri, Mar 18, 2016 at 05:02:07PM -0700, Michael Crosby wrote:
> Why travis so mad?

#350 (see [1]).

[1]: https://travis-ci.org/opencontainers/specs/jobs/116976422#L166

**Comment by vbatts** [comment]
#350

**Comment by crosbymichael** [comment]
I rebased this and its good to go now

**Comment by mrunalp** [comment]
LGTM

**Comment by vbatts** [comment]
LGTM

**Pull request merged**
